"""empty message

Revision ID: 1628691a9630
Revises: 12f5ff773c92
Create Date: 2024-06-12 22:06:47.300529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1628691a9630'
down_revision = '12f5ff773c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_token')
    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_contact', sa.String(length=15), nullable=False))
        batch_op.drop_column('business_phno')
        batch_op.drop_column('buy_id')

    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.drop_column('manufacturer_id')

    with op.batch_alter_table('recycler', schema=None) as batch_op:
        batch_op.drop_column('recycler_id')

    with op.batch_alter_table('retailer', schema=None) as batch_op:
        batch_op.drop_column('retailer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer_id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('recycler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recycler_id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('manufacturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer_id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('business_phno', sa.VARCHAR(length=15), nullable=False))
        batch_op.drop_column('business_contact')

    op.create_table('role_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###
