"""empty message

Revision ID: 5eb44850295a
Revises: 0d3ca3fb6039
Create Date: 2024-06-13 10:52:25.465174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb44850295a'
down_revision = '0d3ca3fb6039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.drop_column('business_name')
        batch_op.drop_column('business_contact')
        batch_op.drop_column('business_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_address', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('business_contact', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('business_name', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
