"""empty message

Revision ID: 8e44eefba760
Revises: 5eb44850295a
Create Date: 2024-06-13 11:09:08.156203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e44eefba760'
down_revision = '5eb44850295a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plastic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plastic', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
