"""empty message

Revision ID: a9828a837b14
Revises: b23bc2f45201
Create Date: 2024-06-12 21:32:53.922633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9828a837b14'
down_revision = 'b23bc2f45201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('business_phno', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('business_address', sa.String(length=150), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role_request', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_phno')
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###
