"""empty message

Revision ID: b23bc2f45201
Revises: a2b6dba2bbf7
Create Date: 2024-06-12 20:06:30.865432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23bc2f45201'
down_revision = 'a2b6dba2bbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('business_phno', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('business_address', sa.String(length=150), nullable=False))

    with op.batch_alter_table('retailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('business_phno', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('business_address', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('retailer_id', sa.Integer(), nullable=False))
        batch_op.drop_column('sell_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.alter_column('date_joined',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_joined',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('retailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sell_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('retailer_id')
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_phno')
        batch_op.drop_column('business_name')

    with op.batch_alter_table('buyer', schema=None) as batch_op:
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_phno')
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###
