"""empty message

Revision ID: c4fdc2bd5ab8
Revises: 
Create Date: 2024-07-23 00:21:27.538070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fdc2bd5ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_type')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('contact_no', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=50), nullable=False),
    sa.Column('business_contact', sa.String(length=15), nullable=False),
    sa.Column('business_address', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recycler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=50), nullable=False),
    sa.Column('business_contact', sa.String(length=15), nullable=False),
    sa.Column('business_address', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=50), nullable=False),
    sa.Column('business_contact', sa.String(length=15), nullable=False),
    sa.Column('business_address', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=50), nullable=False),
    sa.Column('business_contact', sa.String(length=15), nullable=False),
    sa.Column('business_address', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('recycler_id', sa.Integer(), nullable=True),
    sa.Column('manufactured_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['recycler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['plastic_id'], ['plastic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_retailer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plastic_id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plastic_id'], ['plastic.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plastic_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('recycler_id', sa.Integer(), nullable=True),
    sa.Column('log', sa.String(length=200), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
    sa.ForeignKeyConstraint(['plastic_id'], ['plastic.id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['recycler.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('plastic_retailer')
    op.drop_table('plastic_buyer')
    op.drop_table('plastic')
    op.drop_table('user_role_request')
    op.drop_table('retailer')
    op.drop_table('recycler')
    op.drop_table('manufacturer')
    op.drop_table('buyer')
    op.drop_table('user')
    op.drop_table('points')
    # ### end Alembic commands ###
